language: ruby

rvm:
  - 1.9.3

branches:
  only:
    - master

env:
  - DB=mysql

gemfile:
  - Gemfile
before_script: 
  - 'cp config/database.yml.sample config/database.yml'
  - 'bundle exec rake db:create db:up > /dev/null'

script: 'bundle exec rake test'

