language: ruby

rvm:
  - 1.9.3

branches:
  only:
    - master

env:
  - DB=mysql

before_script:
  - cp config/database.yml.sample config/database.yml
  - mysql -e 'create database chromotype_test'

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
